### ISSUE TITLE
Evaluator moves focus to VSCode on Linux

### ISSUE THREAD

**Issue by Stick404** [object-Object/HexDebug#4]
A bug found on the HexxyTest server, (and a HexDebug version of 0.2.0) of where you need to connect to the debugger first with the item Debugger, before you can cast with the Evaluator.  Also, a slight QOL note; when a pattern is cast with the Evaluator, it moves the window selection to VS Code, meaning you need to click again on Minecraft to continue to cast.

**Comment by object-Object** [comment]
It's intentional that the evaluator doesn't work when not debugging; logically it wouldn't make sense, since it uses the stack and ravenmind of the debug session.

I'm not able to repro the other issue. Can you give more details or a video?

**Comment by Stick404** [comment]
At point 0:28 and point 0:37 the window re-selection becomes a problem, it's a small bug (happening only once in about 4ish patterns it looks like), but it can still throw off the flow of casting. https://stick404.mindlesstoys.com/quickfileshare/DebuggerBug.mp4 (had to upload it to my site, since it was bigger than 10 MB)

**Comment by object-Object** [comment]
![image](https://github.com/object-Object/HexDebug/assets/37044997/18c7a76f-8fca-4032-ab35-058ffcd9fbd7)

(thanks chloe!)
