### ISSUE TITLE
[Quilt 1.19.2] Doesn't recognize Quilt Kotlin Libraries as being equivalent to Fabric Language Kotlin.

### ISSUE THREAD

**Issue by jojotastic777** [object-Object/HexDebug#7]
Trying to install HexDebug on Quilt with Quilt Kotlin Libraries instead of Fabric Language Kotlin results in the game failing to launch with the following error:
```
---- Quilt Loader: Failed to load ----
Date/Time: 2024/06/23 11:21:51.1339 [-0700]
Quilt Loader Version: 0.26.0

-- Error 1 --

HexDebug requires version [1.9.4+kotlin.1.8.21, ∞) of fabric-language-kotlin, which is missing!

- <mods>/hexdebug-fabric-0.2.2+1.19.2.jar
```

Interestingly, if I mangle the jar file to remove the dependency on `fabric-language-kotlin` from `fabric.mod.json`, the game loads just fine, likely because QKL is supposed to be *compatible* with FLK.

In case they might be needed, I've uploaded the full logs [here](https://mclo.gs/cXIBewO).

**Comment by object-Object** [comment]
Not sure why Quilt doesn't show this in the *main* error message, but it says this on line 305 of the logs:
```
HexDebug requires at least version 1.9.4 kotlin.1.8.21 or any newer version of fabric-language-kotlin, but only a different version is present: 1.9.0 kotlin.1.8.0
```
Try also installing `quilt-kotlin-libraries-core` from https://modrinth.com/mod/qkl/version/4.0.0+kt.1.9.23+flk.1.10.19 in addition to the version of QKL you currently have.

**Comment by jojotastic777** [comment]
Just tried that, and now quilt is complaining about duplicate mod IDs:
```
---- Quilt Loader: Failed to load ----
Date/Time: 2024/06/23 16:11:52.0982 [-0700]
Quilt Loader Version: 0.26.0

-- Error 1 --

Duplicate mandatory mod ids [qkl]
- <mods>/quilt-kotlin-libraries-4.0.0+kt.1.9.23+flk.1.10.19.jar
- <mods>/quilt-kotlin-libraries-1.0.2+kt.1.8.0+flk.1.9.0.jar
```

_Disabling_ the qkl 1.0.2 seems to work, but I don't know if that will break anything else.

**Comment by object-Object** [comment]
`quilt-kotlin-libraries-core`, not `quilt-kotlin-libraries`.

**Comment by jojotastic777** [comment]
Oh, I didn't realize there were two files available there. That worked.
